### ISSUE TITLE
Doesn't work with docker-compose version 2.0

### ISSUE THREAD

**Issue by dominikof** [cpuguy83/docker-grand-ambassador#11]
After update config docker-compose to the version 2.0 ambassador stop working and write in the log files such error:
http://take.ms/cki7L

**Comment by cpuguy83** [comment]
Compose v2 uses docker's new networking features which (should) obviate the need for this.
What's your use-case for using this with the new docker networking features?

**Comment by dominikof** [comment]
Thank you for your response, already figure out and fix all the problem. Thank you again )))
