### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hairyhenderson** [cpuguy83/docker-grand-ambassador#5]
I can't find which (if any) license this is released under... Can you add a LICENSE.md or add something to the README.md with details?

**Comment by cpuguy83** [comment]
Closed by https://github.com/cpuguy83/docker-grand-ambassador/commit/5367b91e206479e14ec2197bbf632e4265d12574

**Comment by hairyhenderson** [comment]
:thumbsup: that was fast!
