### ISSUE TITLE
Could the proxy caveat be causing a 404?

### ISSUE THREAD

**Issue by webkenny** [cpuguy83/docker-grand-ambassador#7]
This could be all me but here's my situation. I'm running tests to an API inside a container. That's not important really because `curl` produces the same thing, a 404 to the endpoints. However, the same exact URL hit from my local machine does not produce a 404. Is this somehow related to the proxy behavior of grand ambassador? I'm lost honestly. Here's the relevant entries from the called container:

`web_1        | 192.168.59.3 - - [16/Jun/2015:15:48:46 +0000] "GET /notifications HTTP/1.1" 200 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3"`

`web_1        | 172.17.0.31 - - [16/Jun/2015:15:50:40 +0000] "GET /notifications HTTP/1.1" 404 168 "-" "curl/7.35.0"`

Note the only difference here is the IP it's calling on. It's clearly making the connection for it to even log in the other container.

I'm grasping at straws here but curious if there's anything I need to be aware of when using the ambassador setup that isn't obviously apparent to me.

Thanks a ton. Great tool here, by the way. Very useful!

**Comment by cpuguy83** [comment]
Hmm, it shouldn't be causing a 404 unless something is dropped while proxying.
But the proxy used is the same proxy that docker uses when calling `docker run -p 80` (for example).

**Comment by webkenny** [comment]
Yeah I think you're right. Thanks for the reply. I've never seen anything like it before, honestly. So frustrating but thanks again for all your work! I'll report back if I do indeed find it has something to do with the proxy.
